//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvDatabaseEntities : DbContext
    {
        public CvDatabaseEntities()
            : base("name=CvDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADMİN> TBL_ADMİN { get; set; }
        public virtual DbSet<TBL_CERTIFICATES> TBL_CERTIFICATES { get; set; }
        public virtual DbSet<TBL_COMMUNİCATİON> TBL_COMMUNİCATİON { get; set; }
        public virtual DbSet<TBL_EDUCATİON> TBL_EDUCATİON { get; set; }
        public virtual DbSet<TBL_EXPERİENCES> TBL_EXPERİENCES { get; set; }
        public virtual DbSet<TBL_İNTEREST> TBL_İNTEREST { get; set; }
        public virtual DbSet<TBL_SKİLL> TBL_SKİLL { get; set; }
        public virtual DbSet<TBL_MEDİA> TBL_MEDİA { get; set; }
    }
}
