//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MEDİA
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string LİNK { get; set; }
        public string İCON { get; set; }
        public Nullable<bool> Situation { get; set; }
    }
}
