//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_COMMUNİCATİON
    {
        public short ID { get; set; }
        public string FULLNAME { get; set; }
        public string MAİL { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
