//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_ADMİN
    {
        public short ID { get; set; }

        [Required(ErrorMessage = "Bu alanın doldurulması zorunludur.")]
        [StringLength(30,ErrorMessage ="Lütfen 30 karakterden fazla veri girmeyiniz.")]
        public string PASSWORD { get; set; }
 
        [Required(ErrorMessage ="Bu alanın doldurulması zorunludur.")]
        [StringLength(30, ErrorMessage = "Lütfen 30 karakterden fazla veri girmeyiniz.")]
        public string USERNAME { get; set; }
    }
}
