//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EDUCATİON
    {
        public short ID { get; set; }
        public string TİTLE { get; set; }
        public string SUBTİTLE1 { get; set; }
        public string SUBTİTLE2 { get; set; }
        public string GNO { get; set; }
        public string DATE { get; set; }
    }
}
