//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ABOUT
    {
        public short ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string ADRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string MAİL { get; set; }
        public string DESCRİPTİON { get; set; }
        public string İMAGE { get; set; }
    }
}
